// Code generated by grpc-kit-cli. DO NOT EDIT.

package handler

import (
	"context"

	"google.golang.org/grpc/codes"
	hz "google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/status"
)

// HealthCheck 用于健康检测
func (m Microservice) HealthCheck(ctx context.Context, req *hz.HealthCheckRequest) (*hz.HealthCheckResponse, error) {
	if req.Service == m.code {
		return &hz.HealthCheckResponse{
			Status: hz.HealthCheckResponse_SERVING,
		}, nil
	}

	return nil, status.Error(codes.NotFound, "unknown service")
}