name: Test Kubernetes
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: |
          RELEASE="v1.26.7"
          ARCH="amd64"
          sudo curl -L --remote-name-all https://dl.k8s.io/release/${RELEASE}/bin/linux/${ARCH}/kubeadm
          sudo chmod +x kubeadm
          sudo IMGS=$(./kubeadm config images list)
          sudo for i in ${IMGS}; do echo $i; done
      - run: sudo ./kubeadm config images list
