name: Test Kubernetes
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: sudo apt-get install -y kubeadm
      - run: sudo kubeadm config images list
